export const mockProducts = [
  {
    id: 1,
    nomeProduto: "REBANHO PEC",
    descricao: "Suplemento mineral adensado para bovinos de corte",
    imagem: {
      src: "https://realh.com.br/wp-content/uploads/2024/10/REBANHO-PEC-min.png",
      alt: "Imagem do produto",
      width: 284,
      height: 355,
    },
    categoria: "REBANHO",
    link: { link: "#" },
  },
  {
    id: 2,
    nomeProduto: "REBANHO PEC",
    descricao: "Suplemento mineral adensado para bovinos de corte",
    imagem: {
      src: "https://realh.com.br/wp-content/uploads/2024/10/REBANHO-PEC-min.png",
      alt: "Imagem do produto",
      width: 284,
      height: 355,
    },
    categoria: "REBANHO",
    link: { link: "#" },
  },
  {
    id: 3,
    nomeProduto: "REBANHO PEC",
    descricao: "Suplemento mineral adensado para bovinos de corte",
    imagem: {
      src: "https://realh.com.br/wp-content/uploads/2024/10/REBANHO-PEC-min.png",
      alt: "Imagem do produto",
      width: 284,
      height: 355,
    },
    categoria: "REBANHO",
    link: { link: "#" },
  },
  {
    id: 4,
    nomeProduto: "REBANHO PEC",
    descricao: "Suplemento mineral adensado para bovinos de corte",
    imagem: {
      src: "https://realh.com.br/wp-content/uploads/2024/10/REBANHO-PEC-min.png",
      alt: "Imagem do produto",
      width: 284,
      height: 355,
    },
    categoria: "REBANHO",
    link: { link: "#" },
  },
  {
    id: 5,
    nomeProduto: "REBANHO PEC",
    descricao: "Suplemento mineral adensado para bovinos de corte",
    imagem: {
      src: "https://realh.com.br/wp-content/uploads/2024/10/REBANHO-PEC-min.png",
      alt: "Imagem do produto",
      width: 284,
      height: 355,
    },
    categoria: "REBANHO",
    link: { link: "#" },
  },
  {
    id: 6,
    nomeProduto: "REBANHO PEC",
    descricao: "Suplemento mineral adensado para bovinos de corte",
    imagem: {
      src: "https://realh.com.br/wp-content/uploads/2024/10/REBANHO-PEC-min.png",
      alt: "Imagem do produto",
      width: 284,
      height: 355,
    },
    categoria: "REBANHO",
    link: { link: "#" },
  },{
    id: 7,
    nomeProduto: "REBANHO PEC",
    descricao: "Suplemento mineral adensado para bovinos de corte",
    imagem: {
      src: "https://realh.com.br/wp-content/uploads/2024/10/REBANHO-PEC-min.png",
      alt: "Imagem do produto",
      width: 284,
      height: 355,
    },
    categoria: "REBANHO",
    link: { link: "#" },
  },
  {
    id: 8,
    nomeProduto: "REBANHO PEC",
    descricao: "Suplemento mineral adensado para bovinos de corte",
    imagem: {
      src: "https://realh.com.br/wp-content/uploads/2024/10/REBANHO-PEC-min.png",
      alt: "Imagem do produto",
      width: 284,
      height: 355,
    },
    categoria: "REBANHO",
    link: { link: "#" },
  },
  {
    id: 9,
    nomeProduto: "REBANHO PEC",
    descricao: "Suplemento mineral adensado para bovinos de corte",
    imagem: {
      src: "https://realh.com.br/wp-content/uploads/2024/10/REBANHO-PEC-min.png",
      alt: "Imagem do produto",
      width: 284,
      height: 355,
    },
    categoria: "REBANHO",
    link: { link: "#" },
  },{
    id: 10,
    nomeProduto: "REBANHO PEC",
    descricao: "Suplemento mineral adensado para bovinos de corte",
    imagem: {
      src: "https://realh.com.br/wp-content/uploads/2024/10/REBANHO-PEC-min.png",
      alt: "Imagem do produto",
      width: 284,
      height: 355,
    },
    categoria: "REBANHO",
    link: { link: "#" },
  },
]